version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: dalle-bot
    command: python main.py
    ports:
      - "5000"
    volumes:
      - ./:/usr/src/dalle-bot

  ngnix:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "80:80"