version: "3"

services:
  webapp:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: dalle-bot
    command: python bot.py
    ports:
      - "591:591"
    volumes:
      - ./:/usr/src/dalle-bot