version: "3"

services:
  webapp:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: dalle-bot
    command: python main.py
    ports:
      - "8443:8443"
    volumes:
      - ./:/usr/src/dalle-bot